### ISSUE TITLE
Use systemd for Duniter daemon

### ISSUE THREAD

**Issue by M5oul** [YunoHost-Apps/duniter_ynh#21]
Confusing installation state when stopping upgrade script
When the upgrade script is manually stopped in the middle, debian package is removed but from YunoHost point of view it's still installed.
Then, `sudo duniter stop` command fail because `duniter` command no more exist, then because of `set -e`, the script fail.
Then, you stay stucked in a middle of an installed/not installed state

**Comment by M5oul** [comment]
Before doing `sudo duniter stop`, we could check that duniter daemon is running with:
- [daemonize2](https://www.npmjs.com/package/daemonize2)
- doing duniter as a systemd service with command `service duniter status`.

**Comment by M5oul** [comment]
Vincentux encounter an issue restart his server.
Duniter were no more running.
A temporal fix could be to restart duniter daemon.
If we use systemd for Duniter daemon, this issue would be solved.

**Comment by Thatoo** [comment]
+1 . Je demandais à Moul comment faire pour que suite à un reboot de mon raspebry pi, la commande "duniter webrestart" soit lancée automatiquement?

**Comment by M5oul** [comment]
Automatic close.
It's not finish:
Restarting the server do not restart duniter daemon as a service.

**Comment by Insoleet** [comment]
J'utilise un daemon pour faire tourner duniter sur yunohost, voici ma conf : 

```
admin@yunohost:~$ cat /etc/systemd/system/duniter.service 
[Unit]
Description=Duniter node
After=network.target httpd.service
ConditionPathExists=/opt/g1/.config/duniter/duniter_default/duniter.db

[Service]
Group=g1
User=g1
Type=forking
EnvironmentFile=/etc/default/duniter
ExecStart=/usr/bin/duniter webstart
ExecReload=/usr/bin/duniter webrestart
ExecStop=/usr/bin/duniter stop
Restart=no

[Install]
WantedBy=multi-user.target
```

J'ai du créer un utilisateur `g1` pour faire ça : 

```
useradd -s /usr/sbin/nologin -r -M -d /opt/g1 g1
```

L'utilisateur peut avoir un nom différent si besoin.

Je peux ensuite exécuter des commandes dans l'instance de l'utilisateur `g1`, en `root`,  via : 

```
sudo -u g1 duniter logs
```

J'ai n'ai rieu eu d'autre de particulier à faire.

**Comment by paidge** [comment]
Personnellement j’ai du modifié la ligne : 
`EnvironmentFile=/etc/default/duniter`
par
`EnvironmentFile=/usr/bin/duniter`

Comme je faisais tourner mon nœud sous root. Il a fallu que je reparamètre le nœud avec l'utilisateur g1 et que je le resynchronise. Ptet que de déplacer le dossier /root/.config/ vers /opt/g1/.config aurait suffit

**Comment by M5oul** [comment]
https://duniter.org/fr/wiki/duniter/lancement-au-boot/
