### ISSUE TITLE
Cesium+

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/duniter_ynh#45]
Would it be possible to be able to activate/deactivate Cesium+ in the wrapped Cesium?
Now, I don't see how to do that? but in other Cesium, even Cesium I installed on my Yunohost, we can choose to have it or not...

If, for some reason, it isn't possible, then, the issue about a tile in yunohost for the wrapped Cesium, https://github.com/YunoHost-Apps/duniter_ynh/issues/44 , is not as important as being able to install directly a Cesium app from https://github.com/YunoHost-Apps/cesium_ynh to make it accessible to other users. In that case, I would not put the wrapped Cesium public.

**Comment by M5oul** [comment]
> Would it be possible to be able to activate/deactivate Cesium+ in the wrapped Cesium?

Good question. May be on the settings. I think it must be configured on the ES API.

> If, for some reason, it isn't possible, then, the issue about a tile in yunohost for the wrapped Cesium, #44 , is not as important as being able to install directly a Cesium app from https://github.com/YunoHost-Apps/cesium_ynh to make it accessible to other users. In that case, I would not put the wrapped Cesium public.

I repeat. This app do not works due to HTTPS/HTTP mix on web browser such as Firefox.
Could you make it works? I don't. I do not recommended it.

**Comment by c-geek** [comment]
If I am right, you can enable Cesium+ in the Cesium embedded with Duniter (YunoHost package) by editing your `/opt/duniter/sources/node_modules/duniter-ui/public/cesium/config.js` file and replacing:

```json
"plugins": {}
```

By 

```json
"plugins": { 
  "es": { 
    "enable": true, 
    "askEnable": false, 
    "host": "g1.data.duniter.fr", 
    "port": "443", 
    "notifications": { 
      "txSent": true, 
      "txReceived": true, 
      "certSent": true, 
      "certReceived": true 
    } 
  } 
}
```

Be cautious: Cesium+ is a centralized entity which collects and restitues the informations sent by its users. These data are *not* written in the blockchain. Use it with this warning in mind.

**Comment by Thatoo** [comment]
> I repeat. This app do not works due to HTTPS/HTTP mix on web browser such as Firefox.
> Could you make it works? I don't. I do not recommended it.

For me it works in HTTPS... except Cesium+ :-)

**Comment by M5oul** [comment]
Yep, you could. Go ahead!
