### ISSUE TITLE
Fix duniter version and check checksum

### ISSUE THREAD

**Issue by M5oul** [YunoHost-Apps/duniter_ynh#50]
- Fix duniter version: as duniter is now enough stable, we may fix the version number.
- [Check build checksum](https://github.com/duniter/duniter/issues/866) with YunoHost 2.6 [helper which set-up sources and check integrity](https://github.com/YunoHost/yunohost/blob/unstable/data/helpers.d/utils#L28-L138).
  - Debian package installation need to be handled.
  - Duniter 1.3 needs to be released with https://github.com/duniter/duniter/issues/866

**Comment by c-geek** [comment]
About the build checksum, here is a bit of prospective: https://github.com/duniter/duniter/issues/866#issuecomment-301893609

**Comment by M5oul** [comment]
Ok, finally even extraction and checksum helper won't be adapted.
A special helper will be needed to check the checksum.
There is tools to parse `yaml` files with bash: [1](https://gist.github.com/pkuczynski/8665367), [2](https://gist.github.com/epiloque/8cf512c6d64641bde388), [3](https://github.com/ash-shell/yaml-parse).

So, yes, it will be ok.

**Comment by M5oul** [comment]
The version is fix since Duniter repository moved to GitLab.
There is no checksum to check.
