### ISSUE TITLE
Failed to install with the CI

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/duniter_ynh#59]
Hi,

Your app doesn't work for the moment.
It's fail on the installation tests on our CI.
https://ci-apps.yunohost.org/jenkins/job/duniter%20(Community)/19/consoleFull

Your app will be moved at 'inprogress' status by the next week, on 15 of july.

**Comment by tierce** [comment]
The installation from the Web GUI does no work.

```
Exécution du script « /var/cache/yunohost/from_file/duniter_ynh-6fa1bb77bab028bd6d840680bdcc59cd37fe59a6/scripts/remove »...

sed: can't read /opt/duniter/sources/node_modules/duniter-ui/public/cesium/config.js: No such file or directory

+ sudo sed -i 's@"host".*@"host": "duniter.computhings.be",@' /opt/duniter/sources/node_modules/duniter-ui/public/cesium/config.js

```

But the installation **is successful from he command line**.

`yunohost app install https://github.com/duniter/duniter_ynh`

**Comment by M5oul** [comment]
Fixed upstream after re factor changes.
