### ISSUE TITLE
glibc

### ISSUE THREAD

**Issue by nvallas** [YunoHost-Apps/duniter_ynh#60]
hello

raspberry 3
Debian 8.0 32bit (Linux 4.9.51-v7+)
yunohost manual install (https://yunohost.org/#/install_manually_fr)
yunohost 2.7.2

error during install
```bash
Attention : Error: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /opt/duniter/node_modules/sqlite3/lib/binding/node-v48-linux-arm/node_sqlite3.node)
```

**Comment by M5oul** [comment]
Could you try with [this solution](https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error).

**Comment by M5oul** [comment]
Should be fixed with https://forum.duniter.org/t/beta-test-duniter-1-6-ws2p/3247/119?u=cgeek
