### ISSUE TITLE
111 Connection refused nginx error

### ISSUE THREAD

**Issue by Folatt** [YunoHost-Apps/duniter_ynh#61]
See https://forum.yunohost.org/t/duniter-web-interface-502-bad-gateway/3686

**Comment by M5oul** [comment]
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#1xx_Informational_responses

>101 Switching Protocols
    The requester has asked the server to switch protocols and the server has agreed to do so.[6]

**Comment by Folatt** [comment]
The problem is that after install Duniter does not start automatically.

**Comment by M5oul** [comment]
I am closing. Feel free to reopen.
