### ISSUE TITLE
Impossible de mettre à jour

### ISSUE THREAD

**Issue by vincentux** [YunoHost-Apps/duniter_ynh#65]
Impossible de mettre à jour l'application...

```
sudo yunohost app upgrade duniter -u https://github.com/duniter/duniter_ynh
Attention : Mise à jour de l'application duniter...
Erreur : Impossible de mettre à jour duniter
Erreur : Aucune application à mettre à jour

```

**Comment by M5oul** [comment]
Et avec https://github.com/YunoHost-Apps/duniter_ynh ?
Après, faut mettre à jour le paquet manuellement depuis qu’on est passé à GitLab.
Du coup, tu aura la v1.6.22.

**Comment by vincentux** [comment]
Et avec https://github.com/YunoHost-Apps/duniter_ynh ?
J'ai pas essayé ce liens... :/
Du coup je suis passé en manuel.

**Comment by PatriceF31** [comment]
Et avec https://github.com/YunoHost-Apps/duniter_ynh ?Et avec https://github.com/YunoHost-Apps/duniter_ynh ?
J'ai essayé, même message : 
Attention : Mise à jour de l'application duniter...
Erreur : Impossible de mettre à jour duniter
Erreur : Aucune application à mettre à jour

**Comment by PatriceF31** [comment]
dans : scripts/functions.sh

REMOVE_DUNITER () {
# Stop duniter daemon if running
**sudo** duniter status
if [ `echo "$?"` == 0 ]; then
    **sudo** duniter stop
fi

Je crois que ces les 2 sudo entre les 2 ** qui doivent être enlevé.

**Comment by PatriceF31** [comment]
oups : Les sudo en gras...

**Comment by M5oul** [comment]
Duniter est lancé avec l’utilisateur `root`, du coup il faut conserver `sudo`.
Honnêtement, je vois pas d’où vient le problème.

**Comment by M5oul** [comment]
I am closing. Feel free to reopen.
