### ISSUE TITLE
Update ?

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/duniter_ynh#67]
Is this package still maintained ?
How can we help to update it ?

**Comment by M5oul** [comment]
I am missing time to maintain it actively.
What would be great to improve is:
- use a YunoHost helper to run duniter with a non-root user for security reasons (I would like to do it) that would allows #39.
- set-up (upstream in priority, in the Debian package) a systemd file #21.
- Clean and update scripts to use last packaging conventions with YunoHost helpers.
- … and more, but that seems to be the most important from my point of view.

**Comment by M5oul** [comment]
Completed with the latest refactoring.
