### ISSUE TITLE
Link to the armv7l stretch debian package is wrong

### ISSUE THREAD

**Issue by rodinux** [YunoHost-Apps/duniter_ynh#88]
I have try update with the next version v1.8.0 without success. I have delete previous version and try to install but still an error with strecth. Does we need wait the upgrade with Buster for Yunohost ?
here is the logs of the fail: https://paste.yunohost.org/raw/ihisemihij

**Comment by M5oul** [comment]
It looks like I haven't see that the name of the package changed: `-stretch` was added to `duniter-server-v1.8.0-linux-armv7l*-stretch*.deb`.

cf https://forum.duniter.org/t/nouvelle-version-stable-de-duniter-v1-8-0/7377/126.

Can you try again that it solves it?

**Comment by rodinux** [comment]
> Thanks for the report!
> 
> I haven't see that the name of the package changed: `-stretch` was added to `duniter-server-v1.8.0-linux-armv7l*-stretch*.deb`.
> 
> cf https://forum.duniter.org/t/nouvelle-version-stable-de-duniter-v1-8-0/7377/127.
> 
> Can you try again that it solves it?

I will try later, I have changed my server with a raspberry Pi4 and Buster version and I am waiting for an external hard disk before testing more apps in development.
