### ISSUE TITLE
Handle new permission system introduced in YnH v3.7/v4.1: BMA not accessible, Admin accessible to visitors

### ISSUE THREAD

**Issue by M5oul** [YunoHost-Apps/duniter_ynh#89]
### Reported twice
- https://forum.duniter.org/t/bma-protege-derriere-le-sso-depuis-yunohost-v3-7/7409
- https://forum.duniter.org/t/how-to-access-bma-on-my-own-duniter-node-installed-on-yunohost/7623

### New permission system
- [Groups and permissions doc](https://yunohost.org/en/packaging_apps_permissions)
- [Permission helpers doc](https://yunohost.org/en/packaging_apps_helpers#permission)
- [exemple_ynh: New permissions system usage](https://github.com/YunoHost/example_ynh/blob/611e69cd71e2dea32f8838afee23dcce09ceac75/scripts/install#L341-L363)

**Comment by M5oul** [comment]
I fixed the issue of this ticket. I let it open to support the new permission system.
The new permission system is not supporting the protection for two paths for an admin user.
This support has to be added in `ynh_permission_create` helper to proceed.

**Comment by Thatoo** [comment]
Will be following this issue closely :-)

**Comment by duckwoqei** [comment]
There was a typo in the link provided, the correct one:

sudo yunohost app upgrade duniter -u https://github.com/YunoHost-Apps/duniter_ynh/tree/89_new_permission_system

**Comment by duckwoqei** [comment]
Get an error in upgrading, both as admin and root:

Info: WARNING - Permission 'duniter.admin' not found
Info: ERROR - Could not upgrade duniter: An error occurred inside the app upgrade script
Error: The operation 'Upgrade the 'duniter' app' could not be completed. Please share the full log of this operation using the command 'yunohost log display 20210404-220805-app_upgrade-duniter --share' to get help
root@sis:/home/admin# yunohost log display 20210404-220805-app_upgrade-duniter --share
Info: This log is now available via https://paste.yunohost.org/raw/ajajijaref

**Comment by Thatoo** [comment]
I have tried
`sudo yunohost app upgrade duniter -u https://github.com/YunoHost-Apps/duniter_ynh/tree/89_new_permission_system`
it says there is no such branch
and then I tried 
`sudo yunohost app upgrade duniter -u https://github.com/YunoHost-Apps/duniter_ynh/tree/master`
because I saw you merged things in master but the update failed.
Here is the log : https://paste.yunohost.org/raw/pabudugisu

**Comment by Thatoo** [comment]
Today, I could update with
`sudo yunohost app upgrade duniter -u https://github.com/YunoHost-Apps/duniter_ynh/tree/master`
@M5oul : it seems like people can't reach https://g1.leprette.fr/webui anymore. However, I have two tiles in the yunohost interface, "duniter" and "duniter (adminstration)". Not a big issue, just to mention.

**Comment by M5oul** [comment]
This issue got fixed before the refactoring. To be checked if the access to BMA for everyone and the web admin to the admin have been maintained.
