### ISSUE TITLE
Duniter is not listed anymore?

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/duniter_ynh#92]
In the diag tool of yunohost, it is written that I should uninstall Duniter as it is not listed anymore in the list app.
Is is discontinued? unmaintained? For safety reason, should it be uninstall from yunohost servers?

**Comment by M5oul** [comment]
Yes, Duniter package has been reworked and [added back as working state](https://github.com/YunoHost/apps/commit/e23069d8c10bbc840ba022019e34f3e5377f7885).
